In [1]:
import pandas as pd
import sqlite3

In [2]:
# Creating a database connection
conn = sqlite3.connect("inventory.db")

In [3]:
# check the table present in your database
table = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'",conn)
table

              name
0  amazon_sales.xl
1         BMW_Cars
2        furniture
3  Global_Shopping

In [9]:
for tables in table['name']:
    print('-'* 50,tables,'-'* 50)
    print("Count of the records",pd.read_sql(f"select count(*) as count from `{tables}`",conn)['count'].values[0])
    display(pd.read_sql(f"select * from `{tables}`",conn))

-------------------------------------------------- amazon_sales.xl --------------------------------------------------
Count of the records 15000

,Row_ID,Order_ID,Customer_ID,Date,Product_Category,Product_Name,Quantity,Unit_Price_INR,Total_Sales_INR,Payment_Method,Delivery_Status,Review_Rating,Review_Text,State,Country
0,1,ORD100000,CUST2796,1/25/2025,Home & Kitchen,Cookware Set,2,25574.41,51148.82,Credit Card,Returned,1,Waste of money,Sikkim,India
1,2,ORD100001,CUST9669,8/28/2025,Beauty,Hair Dryer,1,19361.41,19361.41,Debit Card,Returned,5,Excellent product!,Telangana,India
2,3,ORD100002,CUST5808,2/27/2025,Electronics,Tablet,3,38476.22,115428.66,Cash on Delivery,Delivered,3,Fair deal,Nagaland,India
3,4,ORD100003,CUST5889,2/24/2025,Electronics,Headphones,5,38145.72,190728.60,Credit Card,Delivered,5,Highly recommend!,Assam,India
4,5,ORD100004,CUST9005,6/15/2025,Clothing,Saree,5,45940.98,229704.90,UPI,Delivered,5,Highly recommend!,Odisha,India
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,14996,ORD114995,CUST2822,4/12/2025,Beauty,Lipstick,4,36421.54,145686.16,UPI,Delivered,1,Never buying again,Gujarat,India
14996,14997,ORD114996,CUST6143,8/29/2025,Beauty,Shampoo,4,18158.02,72632.08,Debit Card,Delivered,4,Satisfied with the product,Meghalaya,India
14997,14998,ORD114997,CUST6747,1/27/2025,Books,Science Textbook,1,38864.05,38864.05,UPI,Delivered,1,Waste of money,Sikkim,India
14998,14999,ORD114998,CUST2748,6/21/2025,Beauty,Hair Dryer,3,32658.62,97975.86,Cash on Delivery,Pending,3,Okay product,Himachal Pradesh,India
14999,15000,ORD114999,CUST9174,8/7/2025,Home & Kitchen,Mixer Grinder,5,45005.57,225027.85,Cash on Delivery,Pending,4,Good quality,Bihar,India

-------------------------------------------------- BMW_Cars --------------------------------------------------
Count of the records 100

,Row_id,year,month,country,model,segment,engine_type,price_usd,marketing_spend_usd,dealership_count,fuel_price_usd,gdp_growth_percent,interest_rate_percent,competition_index,units_sold
0,1,2015-08-31,1,"Australia, Melbourne",X1,SUV,Petrol,82234,315372,96,0.97,6.29,1.2,8,324
1,2,2018-10-03,8,"Australia, Sydney",i4,Sedan,Electric,82291,447798,234,0.97,6.29,1.2,7,556
2,3,2023-02-09,12,"USA, Washington",5 Series,Electric,Hybrid,40594,259755,25,0.97,6.29,1.2,7,152
3,4,2019-06-22,11,"Australia, Adelaide",i7,SUV,Electric,42371,323541,319,0.97,6.29,1.2,5,730
4,5,2020-04-11,12,"Brazil, BrasÃ­lia",X5,SUV,Diesel,82315,482015,367,0.97,6.29,1.2,2,1156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,2023-09-29,7,"USA, Washington",3 Series,Sedan,Hybrid,62241,403972,198,0.97,6.29,1.2,8,508
96,97,2016-10-26,3,"China, Bajing",i7,Electric,Diesel,50540,348276,355,0.97,6.29,1.2,5,1177
97,98,2015-10-17,11,"Canada, Toronto",3 Series,SUV,Hybrid,107255,427864,239,0.97,6.29,1.2,6,630
98,99,2018-08-18,8,"Brazil, Salvador",i4,SUV,Diesel,99757,348254,264,0.97,6.29,1.2,1,845
99,100,2019-05-17,3,"Japan, Tokyo",X3,SUV,Electric,76203,239826,245,0.97,6.29,1.2,6,880

-------------------------------------------------- furniture --------------------------------------------------
Count of the records 9994

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

-------------------------------------------------- Global_Shopping --------------------------------------------------
Count of the records 29999

,Row_ID,Category,City,Country,Customer_ID,Customer_Name,Discount,Market,Order_ID,Order_Priority,...,ID,Sales,Segment,Ship_Mode,Shipping_Cost,State,Sub_Category,Year,Market2,weeknum
0,1,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,CA-2011-130813,High,...,36624,19,Consumer,Second Class,4.37,California,Paper,2011,North America,2
1,2,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,CA-2011-148614,Medium,...,37033,19,Consumer,Standard Class,0.94,California,Paper,2011,North America,4
2,3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,CA-2011-118962,Medium,...,31468,21,Consumer,Standard Class,1.81,California,Paper,2011,North America,32
3,4,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,CA-2011-118962,Medium,...,31469,111,Consumer,Standard Class,4.59,California,Paper,2011,North America,32
4,5,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,CA-2011-146969,High,...,32440,6,Consumer,Standard Class,1.32,California,Paper,2011,North America,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29994,29995,Office Supplies,Mamak,Turkey,JD-58953,Jonathan Doherty,0.6,EMEA,TU-2014-3610,Critical,...,44194,210,Corporate,First Class,60.04,Ankara,Appliances,2014,EMEA,53
29995,29996,Office Supplies,Mamak,Turkey,JD-58953,Jonathan Doherty,0.6,EMEA,TU-2014-3610,Critical,...,44196,10,Corporate,First Class,2.79,Ankara,Envelopes,2014,EMEA,53
29996,29997,Office Supplies,Silivri,Turkey,VF-117152,Vicky Freymann,0.6,EMEA,TU-2011-2530,Medium,...,42944,15,Home Office,Second Class,1.78,Istanbul,Supplies,2011,EMEA,16
29997,29998,Office Supplies,Esenyurt,Turkey,JS-59403,Joni Sundaresam,0.6,EMEA,TU-2011-3360,Critical,...,46898,42,Home Office,First Class,11.46,Istanbul,Binders,2011,EMEA,18
29998,29999,Office Supplies,Esenyurt,Turkey,ES-40802,Erin Smith,0.6,EMEA,TU-2011-4480,High,...,48896,113,Corporate,First Class,12.34,Istanbul,Appliances,2011,EMEA,26