In [1]:
import pandas as pd
import os
from sqlalchemy import create_engine
import logging
import time

os.makedirs("logs", exist_ok=True)

logging.basicConfig(
    filename="logs/ingestion_db.log",
    level=logging.DEBUG,
    format="%(asctime)s - %(levelname)s - %(message)s",
    filemode="a"
)

logging.info("Logging system started successfully.")

In [2]:
engine = create_engine("sqlite:///inventory.db")

In [3]:
def ingest_db(df,table_name,engine):
    df.to_sql(table_name,con = engine, if_exists='replace',index=False)

folder_path = r"D:\Project.csv"
for file in os.listdir(folder_path):
    if file.endswith(".csv"):
        full_path = os.path.join(folder_path,file)
        df = pd.read_csv(full_path,encoding='latin1')
        print(df.shape)
        ingest_db(df,file[:-4],engine)

(15000, 15)
(100, 15)
(9994, 17)
(29999, 24)

In [4]:
# Logging the data with time stamp
def load_raw_data():
    start = time.time()
    folder_path = r"D:\Project.csv"
    for file in os.listdir(folder_path):
        if file.endswith(".csv"):
            full_path = os.path.join(folder_path,file)
            df = pd.read_csv(full_path,encoding='latin1')
            logging.info(f'logging {file} in a database')
            ingest_db(df,file[:-4],engine)
    end = time.time()
    total_time = (end -start) / 60
    logging.info('ingestion is completed')
    logging.info(f'Total time taken: {total_time} minuit')

if __name__ == "__main__":
    load_raw_data()

In [5]:
pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", engine)

              name
0  amazon_sales.xl
1         BMW_Cars
2        furniture
3  Global_Shopping

In [6]:
pd.read_sql("SELECT COUNT(*) FROM Global_Shopping;", engine)

   COUNT(*)
0     29999